
spring:  datasource:    url: jdbc:oracle:thin:@172.16.0.90:1521:area247dev
    username: CONTENEDOR
    password: CONTENEDOR
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:    hibernate:      ddl-auto: none
    show-sql: false
    properties:
      hibernate: 
        dialect: org.hibernate.spatial.dialect.oracle.OracleSpatial10gDialect
        current_session_context_class: org.springframework.orm.hibernate4.SpringSessionContext
    database-platform: org.hibernate.dialect.Oracle10gDialect